### ISSUE TITLE
Errors when compiling for Flutter Web

### ISSUE THREAD

**Issue by GreenAppers** [jspschool/tweetnacl-dart#1]
[error] The integer literal '0x428a2f98d728ae22' can't be represented exactly in JavaScript. The nearest value that can be represented exactly is '0x428a2f98d728b000'. (package:tweetnacl/src/tweetnacl_base.dart, line 2182, col 5)
[error] The integer literal '0x7137449123ef65cd' can't be represented exactly in JavaScript. The nearest value that can be represented exactly is '0x7137449123ef6400'. (package:tweetnacl/src/tweetnacl_base.dart, line 2183, col 5)
...

**Comment by jspschool** [comment]
Thank you.
